name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio
          
      - name: Run Python tests
        run: |
          python -m pytest tests/ -v
          
      - name: Test MCP server startup
        run: |
          timeout 10s python src/main.py || true
          
      - name: Run demo script
        run: |
          python demo_script.py

  vscode-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install VSCode extension dependencies
        working-directory: vscode-extension
        run: |
          npm install
          npm install -g @vscode/vsce
          
      - name: Compile TypeScript
        working-directory: vscode-extension
        run: |
          npm run compile
          
      - name: Lint code
        working-directory: vscode-extension
        run: |
          npm run lint
          
      - name: Package extension
        working-directory: vscode-extension
        run: |
          vsce package

  integration:
    runs-on: ubuntu-latest
    needs: [test, vscode-extension]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Start MCP server in background
        run: |
          python src/main.py &
          sleep 5
          
      - name: Test MCP server endpoints
        run: |
          curl -f http://localhost:8000/health || echo "Health check failed"